---
# tasks file for install-asterisk
- include_tasks: pjsip.yml
  when: use_pjsip

- name: Remove existing install source dir
  file: "path={{ iasterisk_srcdir }} state=absent"

- name: Create install source dir
  file: "path={{ iasterisk_srcdir }} state=directory"

- name: Download and extract Asterisk source
  unarchive: "src={{ iasterisk_url }} dest={{ iasterisk_srcdir }} remote_src=yes extra_opts=--strip-components=1"

- name: Build Asterisk from tarball
  command: "{{ item }} chdir={{ iasterisk_srcdir }}"
  with_items:
    - ./configure --libdir=/usr/lib64
    - make menuselect.makeopts
    - sed -i -e 's/res_snmp//' menuselect.makeopts
    - sed -i -e 's/chan_sip//' menuselect.makeopts
    - sed -i -e 's/res_http_websocket//' menuselect.makeopts
    - make
    - make uninstall
    - make install
    - make config
    - make samples

- name: Create install dir
  file: "path={{ iasterisk_srcdir }} state=directory"

- name: Create sounds dir
  file: "path={{ iasterisk_path_sound }} state=directory"

- name: Download and extract Asterisk sounds
  unarchive: "src={{ iasterisk_url_sounds }} dest={{ iasterisk_path_sound }} remote_src=yes extra_opts=--strip-components=1"
